coaches/urls.py
from django.conf.urls import patterns, url
from coaches.views import CoachesList, CoachView, CoachEdit,\
    CoachAdd, CoachDelete

urlpatterns = patterns('',

                       url(r'^$', CoachesList.as_view(), name="coaches-list"),
                       url(r'^add/$', CoachAdd.as_view(), name="coach-add"),
                       url(r'^edit/(?P<pk>\d+)/$', CoachEdit.as_view(),
                           name="coach-edit"),
                       url(r'^delete/(?P<pk>\d+)/$', CoachDelete.as_view(),
                           name="coach-delete"),
                       url(r'^(?P<pk>\d+)/$', CoachView.as_view(),
                           name="coach-item"),
                       )

pybursa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from pybursa.views import HomeView, ContactView


urlpatterns = patterns('',
                       url(r'^$', HomeView.as_view(),
                           name='index'),
                       url(r'^coaches/', include('coaches.urls')),
                       url(r'^courses/', include('courses.urls')),
                       url(r'^students/', include('students.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^contact/$', ContactView.as_view(),
                           name='contact-us'),
                       url(r'^i18n/', include('django.conf.urls.i18n')),
                       )

students/urls.py
from django.conf.urls import patterns, include, url
from students.views import students_list, students_item, student_edit, student_add, student_delete

urlpatterns = patterns('',

                       url(r'^$', students_list, name="students-list"),
                       url(r'^add/$', student_add, name="student-add"),
                       url(r'^edit/(?P<student_id>\d+)/$', student_edit,
                           name="student-edit"),
                       url(r'^delete/(?P<student_id>\d+)/$', student_delete,
                           name="student-delete"),
                       url(r'^(?P<student_id>\d+)/$', students_item,
                           name="student-item"),
                       )

students/models.py
# coding=utf-8

from django.utils.translation import ugettext_lazy as _
from django.db import models
from courses.models import Course


class Student(models.Model):
    PACKAGE_FIELDS = (
        ('S', 'Standard'),
        ('G', 'Gold'),
        ('V', 'Vip'),
    )

    name = models.CharField(max_length=255, verbose_name=_('Name'))
    surname = models.CharField(max_length=255, verbose_name=_('Surname'))
    date_of_birth = models.DateField(verbose_name=_('Date of birth'))
    email = models.EmailField(verbose_name=_('Email'))
    phone = models.CharField(max_length=15, verbose_name=_('Phone'))
    course = models.ManyToManyField(Course, verbose_name=_('Course'))
    package = models.CharField(max_length=1, choices=PACKAGE_FIELDS,
                               default='S', verbose_name=_('Package'))
    dossier = models.OneToOneField('students.Dossier', blank=True, null=True,
                                   verbose_name=_('Dossier'))

    def __unicode__(self):
        return "%s %s" % (self.name, self.surname)


class Address(models.Model):
    zip = models.CharField(max_length=30, verbose_name=_('Zip'))
    country = models.CharField(max_length=255, verbose_name=_('Country'))
    province = models.CharField(max_length=255, verbose_name=_('Province'))
    region = models.CharField(max_length=255, verbose_name=_('Region'))
    city = models.CharField(max_length=255, verbose_name=_('City'))
    street = models.CharField(max_length=255, verbose_name=_('Street'))
    house = models.CharField(max_length=30, verbose_name=_('House'))

    def __unicode__(self):
        return "%s %s %s %s %s" % (self.zip, self.street, self.house,
                                   self.city, self.country)


class Dossier(models.Model):
    PACKAGE_COLOURS = (
        ('red', 'Red'),
        ('orange', 'Orange'),
        ('yellow', 'Yellow'),
        ('green', 'Green'),
        ('blue', 'Blue'),
        ('indigo', 'Indigo'),
        ('violet', 'Violet'),
    )

    address = models.ForeignKey(Address, verbose_name=_('Address'))
    unloved_courses = models.ManyToManyField(Course, blank=True, null=True,
                                             verbose_name=_('Unloved courses'))
    favorite_colour = models.CharField(max_length=6, choices=PACKAGE_COLOURS,
                                       default='red',
                                       verbose_name=_('Favorite colour'))

    def __unicode__(self):
        return "%s" % self.address

students/views.py
# coding=utf-8

from django.shortcuts import render, get_object_or_404, redirect
from django.utils.translation import ugettext_lazy as _
from django.contrib import messages
from django import forms
from students.models import Student, Dossier, Course


import logging
logger = logging.getLogger(__name__)


class StudentForm(forms.Form):
    CHOICES = (
              ('S', 'Standard'),
              ('G', 'Gold'),
              ('V', 'Vip'),
    )
    student_name = forms.CharField(max_length=100, label=_('Name'))
    student_surname = forms.CharField(max_length=255, label=_('Surname'))
    student_date_of_birth = forms.DateField(label=_('Date of birth'))
    student_email = forms.EmailField(label=_('Email'))
    student_phone = forms.CharField(max_length=15, label=_('Phone'))
    student_course = forms.ModelMultipleChoiceField(Course.objects.all(),
                                                    label=_('Course'))
    student_package = forms.ChoiceField(widget=forms.RadioSelect,
                                        choices=CHOICES, label=_('Package'))
    student_dossier = forms.ModelChoiceField(Dossier.objects.all(),
                                             required=False, label=_('Dossier'))


class StudentModelForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name', 'surname', 'date_of_birth', 'email', 'phone', 'course',
                  'package', 'dossier']
        widgets = {
            'package': forms.RadioSelect,
            'courses': forms.CheckboxSelectMultiple,
        }


def students_list(request):
    students = Student.objects.all()
    page_title = _('Students list')
    return render(request, 'students/list.html', {'students': students,
                                                  'title': page_title})


def students_item(request, student_id):
    student = get_object_or_404(Student, id=student_id)
    page_title = _('Student item')
    return render(request, 'students/item.html', {'student': student,
                                                  'title': page_title})


def student_edit(request, student_id):
    title = _("Student edit item")
    student = get_object_or_404(Student, id=student_id)
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            student.name = form.cleaned_data['student_name']
            student.surname = form.cleaned_data['student_surname']
            student.date_of_birth = form.cleaned_data['student_date_of_birth']
            student.email = form.cleaned_data['student_email']
            student.phone = form.cleaned_data['student_phone']
            student.course = form.cleaned_data['student_course']
            student.package = form.cleaned_data['student_package']
            student.dossier = form.cleaned_data['student_dossier']\
                if form.cleaned_data['student_dossier'] else None

            try:
                student.save()
                messages.success(request, _(student.name + " details updated!"))
            except:
                messages.error(request, _("Update error!"))
        storage = messages.get_messages(request)
        for message in storage:
            logger.debug(message)
        return redirect('student-edit', student.id)
    else:
        form = StudentForm(initial={'student_name': student.name,
                                    'student_surname': student.surname,
                                    'student_date_of_birth': student.date_of_birth,
                                    'student_email': student.email,
                                    'student_phone': student.phone,
                                    'student_course': student.course.all,
                                    'student_package': student.package,
                                    'student_dossier': student.dossier,
                                    })
    return render(request, 'students/edit.html', {'form': form, 'title': title})


def student_add(request):
    title = _("Student add item")
    if request.method == 'POST':
        form = StudentModelForm(request.POST)
        if form.is_valid():
            try:
                student = form.save()
                messages.success(request, _(student.name + " add successfully!"))
            except:
                messages.error(request, _("Profile add error!"))
        storage = messages.get_messages(request)
        for message in storage:
            logger.debug(message)
        return redirect('student-edit', student.id)
    else:
        form = StudentModelForm()
    return render(request, 'students/edit.html',
                  {'form': form, 'title': title})


def student_delete(request, student_id):
    student = get_object_or_404(Student, id=student_id)
    try:
        student.delete()
        messages.success(request, _(student.name + " delete successfully!"))
    except:
        messages.error(request, _("Profile delete error!"))
    storage = messages.get_messages(request)
    for message in storage:
        logger.debug(message)
    return redirect('students-list')

templates/students/base.html
{%  extends "base.html" %}
{% load static %}

{% block header %}
{% include 'header.html' %}
{% endblock %}

templates/students/edit.html
{%  extends "students/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{{ title|capfirst }} {% endblock %}


{% block content %}

    <div class="container">
        <h2>{{ title }}</h2>
        <form  method="post">
            {% csrf_token %}
             {% for field in form %}
             <div class="fieldWrapper">
              {% if field.field.required %}
                   {{ field.errors }}
                   {{ field.label_tag }}
                    <span class="required">*
                      </span>{{ field }}
             {% else %}
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
            {% endif %}
             </div>
             {% endfor %}
        <p><span class="required">*
                      </span> - {% trans "required fields" %}</p>
        <input type="submit" value={% trans "Send" %} />
        </form>
    </div><!-- /.container -->
{% endblock %}

templates/students/item.html
{%  extends "students/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{{ title|capfirst }} {% endblock %}


{% block content %}

    <div class="container">

        <h2>{% trans "Student:" %} {{ student.surname }} {{ student.name }}</h2>
        <ul class="list-group">
          <li class="list-group-item">{% trans "Email:" %} {{ student.email }}</li>
          <li class="list-group-item">{% trans "Phone:" %} {{ student.phone }}</li>
          <li class="list-group-item">{% trans "Course:" %} {% for course in student.course.all %}
                                            {{ course }}{% endfor %}</li>
          <li class="list-group-item">{% trans "Package:" %} {{ student.get_package_display }}</li>
          {% if student.dossier %}
          <li class="list-group-item">{% trans "Address:" %} {{ student.dossier.address }}</li>
              {% if student.dossier.unloved_courses %}
          <li class="list-group-item">{% trans "Unloved courses:" %}
                {%  for course in student.dossier.unloved_courses.all %}
                {{ course }}{% endfor %}</li>
              {% endif %}
          {% endif %}
          <li class="list-group-item">{% trans "Favorite colour:" %} {{ student.dossier.favorite_colour }}</li>
          <li class="list-group-item"><a href="{% url 'student-edit' student.id %}">{% trans "Edit" %}</a>
          <a href="{% url 'student-add' %}">{% trans "Add" %}</a>
          <a href="{% url 'student-delete' student.id %}">{% trans "Delete" %}</a></li>
          {# <li class="list-group-item">Рейтинг: 1</li> #}

        </ul>

    </div><!-- /.container -->
{% endblock %}

templates/students/list.html
{%  extends "students/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{{ title|capfirst }} {% endblock %}


{% block content %}

    <div class="container">
        <h2>{% trans "Students list" %}</h2>
        <ul class="list-group">

          {% for student in students %}
          <li class="list-group-item">
          {{ forloop.counter }}
            <a href="{% url 'student-item' student.id %}">
              {{ student.surname }} {{ student.name }}
            </a><span class="badge"><a href="{% url 'student-delete' student.id %}">{% trans "Delete" %}</a></span>
            <span class="badge"><a href="{% url 'student-add' %}">{% trans "Add" %}</a></span>
            <span class="badge"><a href="{% url 'student-edit' student.id %}">{% trans "Edit" %}</a></span>
          </li>

          {% endfor %}

        </ul>

    </div><!-- /.container -->

{% endblock %}