coaches/urls.py
from django.conf.urls import patterns, url
from coaches.views import CoachesList, CoachView, CoachEdit,\
    CoachAdd, CoachDelete

urlpatterns = patterns('',

                       url(r'^$', CoachesList.as_view(), name="coaches-list"),
                       url(r'^add/$', CoachAdd.as_view(), name="coach-add"),
                       url(r'^edit/(?P<pk>\d+)/$', CoachEdit.as_view(),
                           name="coach-edit"),
                       url(r'^delete/(?P<pk>\d+)/$', CoachDelete.as_view(),
                           name="coach-delete"),
                       url(r'^(?P<pk>\d+)/$', CoachView.as_view(),
                           name="coach-item"),
                       )

courses/urls.py
from django.conf.urls import patterns, url
from courses.views import CoursesList, CourseView, CourseEdit,\
    CourseAdd, CourseDelete


urlpatterns = patterns('',

                       url(r'^$', CoursesList.as_view(), name="courses-list"),
                       url(r'^add/$', CourseAdd.as_view(), name="course-add"),
                       url(r'^edit/(?P<pk>\d+)/$', CourseEdit.as_view(),
                           name="course-edit"),
                       url(r'^delete/(?P<pk>\d+)/$', CourseDelete.as_view(),
                           name="course-delete"),
                       url(r'^(?P<pk>\d+)/$', CourseView.as_view(),
                           name="course-item"),
                       )

pybursa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from pybursa.views import HomeView, ContactView


urlpatterns = patterns('',
                       url(r'^$', HomeView.as_view(),
                           name='index'),
                       url(r'^coaches/', include('coaches.urls')),
                       url(r'^courses/', include('courses.urls')),
                       url(r'^students/', include('students.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^contact/$', ContactView.as_view(),
                           name='contact-us'),
                       url(r'^i18n/', include('django.conf.urls.i18n')),
                       )

courses/models.py
# coding=utf-8

from django.utils.translation import ugettext_lazy as _
from django.db import models


class Course(models.Model):
    LANGUAGES = (
        ('PY', 'Python'),
        ('RU', 'Ruby'),
        ('JS', 'JavaScript'),
    )

    name = models.CharField(max_length=255, verbose_name=_('Name'))
    slug = models.SlugField(max_length=255, blank=True, default="",
                            verbose_name=_('Slug'))
    description = models.CharField(max_length=255, verbose_name=_('Description'))
    lecturer = models.ForeignKey('coaches.Coach', verbose_name=_('Lecturer'))
    assistant = models.ForeignKey('coaches.Coach',  blank=True, null=True,
                                  related_name="course_assistant",
                                  verbose_name=_('Assistant'))
    date_of_start = models.DateField(verbose_name=_('Date of start'))
    date_of_end = models.DateField(verbose_name=_('Date of end'))
    technology = models.CharField(max_length=2, choices=LANGUAGES,
                                  verbose_name=_('Technology'))
    venue = models.ForeignKey('students.Address', blank=True, null=True,
                              verbose_name=_('Venue'))

    def __unicode__(self):
        return "%s" %  self.name

courses/views.py
# coding=utf-8

from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect
from django.utils.translation import ugettext_lazy as _
from django.contrib import messages
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import (CreateView, UpdateView, DeleteView)
from django import forms

from courses.models import Course

import logging
logger = logging.getLogger(__name__)


class CourseModelForm(forms.ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Course
        fields = ['name', 'slug', 'description', 'lecturer', 'assistant',
                  'date_of_start', 'date_of_end', 'technology', "venue"]
        widgets = {
            'technology': forms.RadioSelect
        }


class CourseView(DetailView):
    template_name = 'courses/item.html'
    model = Course


class CoursesList(ListView):
    template_name = 'courses/list.html'
    model = Course
    context_object_name = 'courses'

    def get_context_data(self, **kwargs):
        context = super(CoursesList, self).get_context_data(**kwargs)
        context['title'] = _('Courses list')
        return context


class CourseAdd(CreateView):
    template_name = 'courses/edit.html'
    model = Course
    form_class = CourseModelForm
    success_url = reverse_lazy('courses-list')

    def form_valid(self, form):
        try:
            course = form.save()
            messages.success(self.request, _(course.name + " added successfully!"))
        except:
            messages.error(self.request, _("Add error."))
        storage = messages.get_messages(self.request)
        for message in storage:
            logger.debug(message)
        return super(CourseAdd, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CourseAdd, self).get_context_data(**kwargs)
        context['title'] = _('Course add item')
        return context


class CourseEdit(UpdateView):
    template_name = 'courses/edit.html'
    model = Course
    form_class = CourseModelForm
    success_url = reverse_lazy('courses-list')

    def form_valid(self, form):
        try:
            course = form.save()
            messages.success(self.request, _(course.name + " updated successfully!"))
        except:
            messages.error(self.request, _("Update error."))
        storage = messages.get_messages(self.request)
        for message in storage:
            logger.debug(message)
        return super(CourseEdit, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CourseEdit, self).get_context_data(**kwargs)
        context['title'] = _('Course update item')
        return context


class CourseDelete(DeleteView):
    template_name = 'courses/delete.html'
    model = Course
    success_url = reverse_lazy('courses-list')

    def delete(self, request, *args, **kwargs):
        try:
            course = self.get_object()
            course.delete()
            messages.success(self.request, _(course.name + " deleted successfully!"))
        except:
            messages.error(self.request, _("Delete error."))
        storage = messages.get_messages(self.request)
        for message in storage:
            logger.debug(message)
        return redirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super(CourseDelete, self).get_context_data(**kwargs)
        context['title'] = _('Course delete item')
        return context

templates/courses/base.html
{%  extends "base.html" %}
{% load static %}

{% block header %}
{% include 'header.html' %}
{% endblock %}

templates/courses/delete.html
{%  extends "courses/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{{ title|capfirst }} {% endblock %}


{% block content %}
    <div class="container">
    <h2>{{ title }}</h2>
<form action="" method="post">{% csrf_token %}
    <p>{% trans "Are you sure you want to delete" %} "{{ object }}"?</p>
    <input type="submit" value={% trans "Confirm" %} />
</form>
</div>
{% endblock %}

templates/courses/edit.html
{%  extends "courses/base.html" %}
{% load static %}


{% block title %}{{ title|capfirst }} {% endblock %}


{% block content %}
    <div class="container">
<h2>{{ title }}</h2>
           <form  method="post">
            {% csrf_token %}
            {{ form.as_p }}
        <input type="submit" />
        </form>

    </div><!-- /.container -->
{% endblock %}

templates/courses/item.html
{%  extends "courses/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{{ title|capfirst }} {% endblock %}


{% block content %}
    <div class="container">

        <h2>{%  trans "Course:" %} {{ course.name }}</h2>
        <ul class="list-group">
          <li class="list-group-item">{% trans "Description:" %} {{ course.description }}</li>
          <li class="list-group-item">{% trans "Technology:" %} {{ course.get_technology_display }}</li>
          <li class="list-group-item">{% trans "Lecturer:" %} {{ course.lecturer }}</li>
            {% if course.assistant %}
          <li class="list-group-item">{%  trans "Assistant:" %} {{ course.assistant }}</li>
            {% endif %}
          <li class="list-group-item">{% trans "Date of start:" %} {{ course.date_of_start }}</li>
          <li class="list-group-item">{% trans "Date of end:" %} {{ course.date_of_end }}</li>
            {% if course.venue %}
          <li class="list-group-item">{% trans "Address:" %} {{ course.venue }}</li>
            {% endif %}
          <li class="list-group-item"><a href="{% url 'course-edit' course.id %}">{% trans "Edit" %}</a>
          <a href="{% url 'course-add' %}">{% trans "Add" %}</a>
          <a href="{% url 'course-delete' course.id %}">{% trans "Delete" %}</a></li>
        </ul>

    </div><!-- /.container -->
{% endblock %}

templates/courses/list.html
{%  extends "courses/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{{ title|capfirst }} {% endblock %}


{% block content %}

    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <div class="page-header">
                    <h2 id="tables">{% trans "Courses list" %}</h2>
                </div>

                <div class="bs-component">
                    <table class="table table-striped table-hover ">
                        <thead>
                        <tr>
                            <th>{% trans "Course name" %}</th>
                            <th>{% trans "Date of start" %}</th>
                            <th>{% trans "Date of end" %}</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                       {% for course in object_list %}
                         <tr class="info">
                         <td><a href="{% url 'course-item' course.id %}">
                             {{ course.name }}</a></td>
                         <td>{{ course.date_of_start }}</td>
                         <td>{{ course.date_of_end }}</td>
                         <td><span class="badge"><a href="{% url 'course-edit' course.id %}">{% trans "Edit" %}</a></span>
                             <span class="badge"><a href="{% url 'course-add' %}">{% trans "Add" %}</a></span>
                             <span class="badge"><a href="{% url 'course-delete' course.id %}">{% trans "Delete" %}</a></span>
                         </td>
                         </tr>
                       {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container -->
{% endblock %}