coaches/urls.py
from django.conf.urls import patterns, url
from coaches.views import CoachesList, CoachView, CoachEdit,\
    CoachAdd, CoachDelete

urlpatterns = patterns('',

                       url(r'^$', CoachesList.as_view(), name="coaches-list"),
                       url(r'^add/$', CoachAdd.as_view(), name="coach-add"),
                       url(r'^edit/(?P<pk>\d+)/$', CoachEdit.as_view(),
                           name="coach-edit"),
                       url(r'^delete/(?P<pk>\d+)/$', CoachDelete.as_view(),
                           name="coach-delete"),
                       url(r'^(?P<pk>\d+)/$', CoachView.as_view(),
                           name="coach-item"),
                       )

pybursa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from pybursa.views import HomeView, ContactView


urlpatterns = patterns('',
                       url(r'^$', HomeView.as_view(),
                           name='index'),
                       url(r'^coaches/', include('coaches.urls')),
                       url(r'^courses/', include('courses.urls')),
                       url(r'^students/', include('students.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^contact/$', ContactView.as_view(),
                           name='contact-us'),
                       url(r'^i18n/', include('django.conf.urls.i18n')),
                       )

coaches/models.py
# coding=utf-8

from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.contrib.auth.models import User

from students.models import Dossier


class Coach(models.Model):
    TEACHERS = (
        ('LE', 'Lecturer'),
        ('AS', 'assistant'),
    )
    name = models.CharField(max_length=255, verbose_name=_('Name'))
    surname = models.CharField(max_length=255,  verbose_name=_('Surname'))
    date_of_birth = models.DateField(verbose_name=_('Date of birth'))
    email = models.EmailField(verbose_name=_('Email'))
    phone = models.CharField(max_length=15,  verbose_name=_('Phone'))
    teacher = models.CharField(max_length=2, choices=TEACHERS,
                               verbose_name=_('Teacher'))
    user = models.ForeignKey(User,  verbose_name=_('User'))
    dossier = models.OneToOneField(Dossier, blank=True, null=True,
                                   verbose_name=_('Dossier'))

    def __unicode__(self):
        return "%s %s" % (self.name, self.surname)

coaches/views.py
# coding=utf-8

from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect
from django.utils.translation import ugettext_lazy as _
from django.contrib import messages
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import (CreateView, UpdateView, DeleteView)
from django import forms

from coaches.models import Coach

import logging
logger = logging.getLogger(__name__)


class CoachModelForm(forms.ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Coach
        fields = ['name', 'surname', 'date_of_birth', 'email', 'phone',
                  'teacher', 'user', 'dossier']


class CoachView(DetailView):
    template_name = 'coaches/item.html'
    model = Coach


class CoachesList(ListView):
    template_name = 'coaches/list.html'
    model = Coach
    context_object_name = 'coaches'

    def get_context_data(self, **kwargs):
        context = super(CoachesList, self).get_context_data(**kwargs)
        context['title'] = _('Coaches list')
        return context


class CoachAdd(CreateView):
    template_name = 'coaches/edit.html'
    model = Coach
    form_class = CoachModelForm
    success_url = reverse_lazy('coaches-list')

    def form_valid(self, form):
        try:
            coach = form.save()
            messages.success(self.request, _(coach.name + " added successfully!"))
        except:
            messages.error(self.request, _("Add error."))
        storage = messages.get_messages(self.request)
        for message in storage:
            logger.debug(message)
        return super(CoachAdd, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CoachAdd, self).get_context_data(**kwargs)
        context['title'] = _('Coach add item')
        return context


class CoachEdit(UpdateView):
    template_name = 'coaches/edit.html'
    model = Coach
    form_class = CoachModelForm
    success_url = reverse_lazy('coaches-list')

    def form_valid(self, form):
        try:
            coach = form.save()
            messages.success(self.request, _(coach.name + " updated successfully!"))
        except:
            messages.error(self.request, _("Update error."))
        storage = messages.get_messages(self.request)
        for message in storage:
            logger.debug(message)
        return super(CoachEdit, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CoachEdit, self).get_context_data(**kwargs)
        context['title'] = _('Coach update item')
        return context


class CoachDelete(DeleteView):
    template_name = 'coaches/delete.html'
    model = Coach
    success_url = reverse_lazy('coaches-list')

    def delete(self, request, *args, **kwargs):
        try:
            coach = self.get_object()
            coach.delete()
            messages.success(self.request, _(coach.name + " deleted successfully!"))
        except:
            messages.error(self.request, _("Delete error."))
        storage = messages.get_messages(self.request)
        for message in storage:
            logger.debug(message)
        return redirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super(CoachDelete, self).get_context_data(**kwargs)
        context['title'] = _('Coach delete item')
        return context

templates/coaches/base.html
{%  extends "base.html" %}
{% load static %}

{% block header %}
{% include 'header.html' %}
{% endblock %}

templates/coaches/delete.html
{%  extends "courses/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{{ title|capfirst }} {% endblock %}


{% block content %}
    <div class="container">
        <h2>{{ title }}</h2>
<form action="" method="post">{% csrf_token %}
    <p>{% trans "Are you sure you want to delete" %} "{{ object }}"?</p>
    <input type="submit" value={% trans "Confirm" %} />
</form>
</div>
{% endblock %}

templates/coaches/edit.html
{%  extends "coaches/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{{ title|capfirst }} {% endblock %}


{% block content %}

    <div class="container">
         <h2>{{ title }}</h2>
           <form  method="post">
            {% csrf_token %}
            {{ form.as_p }}
        <input type="submit" value={% trans "Send" %} />
        </form>


    </div><!-- /.container -->
{% endblock %}

templates/coaches/item.html
{%  extends "coaches/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{{ title|capfirst }} {% endblock %}


{% block content %}

    <div class="container">

        <h2>{% trans "Coach:" %} {{ coach.surname }} {{ coach.name }}</h2>
        <ul class="list-group">
          <li class="list-group-item">{% trans "Email:" %} {{ coach.email }}</li>
          <li class="list-group-item">{% trans "Phone:" %} {{ coach.phone }}</li>
          <li class="list-group-item">{% trans "Teacher:" %} {{ coach.get_teacher_display }}</li>
            {% if coach.dossier %}
          <li class="list-group-item">{% trans "Address:" %} {{ coach.dossier.address }}</li>
          <li class="list-group-item">{% trans "Unloved courses:" %}
              {%  for course in coach.dossier.unloved_courses.all %}
              {{ course }}{% endfor %}</li>
          {% endif %}
          <li class="list-group-item">{% trans "Favorite colour:" %} {{ coach.dossier.favorite_colour }}
          <li class="list-group-item"><a href="{% url 'coach-edit' coach.id %}">{% trans "Edit" %}</a>
          <a href="{% url 'coach-add' %}">{% trans "Add" %}</a>
          <a href="{% url 'coach-delete' coach.id %}">{% trans "Delete" %}</a></li>
          {# <li class="list-group-item">Рейтинг: 1</li> #}

        </ul>

    </div><!-- /.container -->
{% endblock %}

templates/coaches/list.html
{%  extends "coaches/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{{ title|capfirst }} {% endblock %}


{% block content %}

    <div class="container">
        <h2>{% trans "Coaches list" %}</h2>
        <ol class="list-group">
          {% for coach in object_list %}
          <li class="list-group-item">
            {{ forloop.counter }}
            <a href="{% url 'coach-item' coach.id %}">
              {{ coach.surname }} {{ coach.name }}
            </a><span class="badge"><a href="{% url 'coach-delete' coach.id %}">{% trans "Delete" %}</a></span>
            <span class="badge"><a href="{% url 'coach-add' %}">{% trans "Add" %}</a></span>
            <span class="badge"><a href="{% url 'coach-edit' coach.id %}">{% trans "Edit" %}</a></span>
          </li>
          {% endfor %}
        </ol>

    </div><!-- /.container -->
{% endblock %}